### PR TITLE
Add a sourcemap option to sass_binary

### PR DESCRIPTION
**Pull request by nex3**

### CODE REVIEW

**Comment by alexeagle** [comment]
Oh too bad I didn't see this before I did it myself today.

I think we should discuss how configurable the rules ought to be. For example, under Bazel what's the use case for turning off sourcemaps? Why should we expose an attribute for that?

Partly I try to be very conservative in what API I expose because it's so much harder to remove/change something than to add it later.

**Comment by nex3** [comment]
> Oh too bad I didn't see this before I did it myself today.

Oops... I should have thought to ping you about it!

> I think we should discuss how configurable the rules ought to be. For example, under Bazel what's the use case for turning off sourcemaps? Why should we expose an attribute for that?

I just tried to match the existing internal `sass_binary` rule. I'd personally be fine with always generating source maps, but I'm worried about the migration cost of removing the option.

**Comment by alexeagle** [comment]
Ah, the way I handle this for other rules is to share an attrs dict,
outputs, action creating helpers, but have a different entry point (rule
declaration) for bazel and blaze. This way there are some attributes which
exist in one and not the other, allowing us to keep backward compat in
google3 but expose a subset we're happier with for external. The only
drawback I know of is that current skydoc doesn't know how to show the
attributes that come from a load'ed dict so the doc is incomplete.

**Comment by nex3** [comment]
Sounds good to me, if you think the tradeoffs are worth it.

**Pull request closed without merging**
