### PR TITLE
Add npm flavor commands to complement yarn

### PR DESCRIPTION
**Pull request by olore**
Some people have an aversion to yarn. I thought this might be helpful.

### CODE REVIEW

**Comment by alexeagle** [comment]
This repo has a `yarn.lock` file, which means everyone working in this repo has to choose yarn. Other repos could make other choices.

However, there's no reason to expose this in the README - I like it better to just say `bazel run :install` - how does a4edb415 look to you?

**Comment by olore** [comment]
This works. Thank you! Your work on this is much appreciated 👍

**Comment by kylecordes** [comment]
@alexeagle  That alias is a very nice improvement, but I still find the need to run the command by hand an area of discomfort. It feels slightly incomplete. How do we get Bazel to understand the dependencies so that it can do this itself?

appcode -> node_modules -> package.json+yarn.lock

**Comment by alexeagle** [comment]
@kylecordes you have that option also - check out how ngrx gets its compile-time deps:
https://github.com/ngrx/platform/blob/master/WORKSPACE#L80

that means you can clone ngrx/platform and `bazel build //...` without needing to run any install step.

However, it has the downside that there's no `node_modules` directory in your project, so other node-based tooling outside of Bazel doesn't work, and also your editor won't pick up the same version of TypeScript which I think is troubling.

My expectation is that casual users getting started want the developer experience of npm (oops did you install) and experienced developers on a large monorepo want the developer experience of Bazel.

As another datapoint we are planning to move angular/angular's build to the latter way.

**Comment by kylecordes** [comment]
@alexeagle Thanks. I think I once knew that, but had forgotten :-)

**Pull request closed without merging**
