### PR TITLE
Remove redundant explicit deps on @rxjs

### PR DESCRIPTION
**Pull request by gregmagolan**

### CODE REVIEW

**Comment by alexeagle** [comment]
This change ought to break the build - there is a direct dependency on rxjs from 'todos/todos.component.ts`

Can you investigate why the strict_deps plugin isn't catching that? It has an exception when files come from node_modules - I guess that's the case here since we use rxjs from npm

**Comment by alexeagle** [comment]
hmm even commenting out that exception for the strict_deps plugin doesn't reproduce the expected behavior.

Same thing @jelbourn reported this morning - could you debug into the strict deps plugin a bit?

**Comment by alexeagle** [comment]
Ping! Not high priority, but we should figure out why this PR is green when it should be red

**Comment by gregmagolan** [comment]
Strict deps issue for `ng_module`: https://github.com/angular/angular/issues/23094

**Pull request closed without merging**
